---
# tasks file for git-download-mautic

- name: "Install Git and other needed packages"
  package: name={{ item }} update_cache=yes 
  with_items: 
  - git
  - php7.0
  - php7.0-mbstring
  - php7.0-mysql
  - libapache2-mod-php7.0
  - php7.0-mcrypt
  - php7.0-curl
  - php7.0-json
  - php7.0-sqlite3
  - php7.0-zip
  - php7.0-xml
  - php-imap
  - php7.0-bcmath
  - php7.0-intl
  - php7.0-odbc
  - php7.0-soap
  - php7.0-gd
  notify: 
  - restart-apache

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: MySQLi
    option: mysqli.allow_local_infile
    value: 0

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: memory_limit
    value: 756M

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: post_max_size
    value: 64M

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: upload_max_filesize
    value: 64M

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: max_input_time
    value: 60

- name: "Changing PHP ini file options"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: max_execution_time
    value: 300

# The timezone for PHP and for the OS need to be set to UTC for sync integrations to work properly
- name: "Set timezone in PHP ini file"
  ini_file: 
    path: /etc/php/7.0/apache2/php.ini
    section: PHP
    option: date.timezone
    value: UTC

# The timezone for PHP and for the OS need to be set to UTC for sync integrations to work properly
- name: 'Set Timezone to UTC'
  timezone:
    name: Etc/UTC

- name: "Clearing out existing web directory"
  file: 
    state: absent 
    path: "{{ web_files_path }}/"

- name: "Re-creating html directory"
  file:
    path: "{{ web_files_path }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0644
    recurse: yes

- name: "Git clone the repo"
  command: git clone {{ git_repo }} html
  args: 
    chdir: "{{ web_files_path }}/.."

- name: Debugging the git_branch variable
  debug: var=git_branch

- name: Debugging the tagged_release_version variable
  debug: var=tagged_release_version

- name: "Checkout the desired release"
  command: git checkout {{ tagged_release_version }}
  args: 
    chdir: "{{ web_files_path }}"
  when: tagged_release_version != ""

- name: "Checkout the desired branch"
  command: git checkout {{ git_branch }}
  args: 
    chdir: "{{ web_files_path }}"
  when: git_branch != ""

- name: "Install Python MySQL bindings required for Ansible MySQL module"
  apt: name=python-mysqldb state=present

- name: MYSQL | Create {{db_name}} database
  mysql_db:
    name: "{{ db_name }}"
    login_password: "{{ mysql_root_password }}"
    state: present
    collation: "utf8_unicode_ci"

- name: MYSQL | Create {{db_name}} user
  mysql_user:
    login_password: "{{ mysql_root_password }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: '%'
    priv: '{{ db_name }}.*:TRIGGER,CREATE ROUTINE,CREATE TEMPORARY TABLES,CREATE VIEW,ALTER ROUTINE,REFERENCES,EVENT,SHOW VIEW,EXECUTE,ALTER,DROP,CREATE,INDEX,SELECT,INSERT,UPDATE,DELETE'
    state: present

- name: "Create and set a swap file if one is not set. Mautic composer sometimes has problems otherwise"
  block:

    - name: Create swap directory
      command: mkdir -p /extraswap

    - name: Create swap space
      command: dd if=/dev/zero of=swapfile bs=1M count=2000
      args:
        chdir: /extraswap

    - name: Create swap space
      command: mkswap swapfile
      args:
        chdir: /extraswap

    - name: Turn swap on
      command: swapon swapfile
      args:
        chdir: /extraswap

    - name: Set swap file permission
      command: chmod 600 swapfile
      args:
        chdir: /extraswap

    - name: Add to fstab
      action: lineinfile dest=/etc/fstab regexp="swapfile" line="/extraswap/swapfile none swap sw 0 0" state=present

    - name: Set swapiness
      sysctl:
        name: vm.swappiness
        value: "1" 

  # Only execute if the swap is not already setup
  when: ansible_swaptotal_mb < 1

- name: "Install Composer program"
  script: ../files/install_composer.sh
  args: 
    creates: /usr/local/bin/composer

- name: "Install Composer packages"
  composer: 
    command: install
    working_dir: "{{ web_files_path }}"
  notify: finish-mautic-permissions

# Removing this temporarily since the local.php file has confidential data in it
#- name: "Deploying Mautic Config Script with Settings"
#  template:
#    src: ../templates/local.php
#    dest: {{ web_files_path }}/app/config/local.php
#    owner: "{{ web_user }}"
#    group: "{{ web_group }}"
#    mode: 0644
#  when: mautic_restore == "yes"

# Will add this back in later after some fixes and testing - leaving it here for now
#- block:
#
#    - name: "Deploy FB Ads to Leads Mautic Plugin"
#      git:
#        repo: 'https://github.com/stancel/MauticFBAdsCustomAudiencesBundle.git'
#        dest: {{ web_files_path }}/plugins/MauticFBAdsCustomAudiencesBundle
#        version: master
#
#    - name: "Deploy FB Ads to Leads Mautic Plugin"
#      git:
#        repo: 'https://github.com/stancel/MauticFBAdsLeadAdsBundle.git'
#        dest: {{ web_files_path }}/plugins/MauticFBAdsLeadAdsBundle
#        version: master
#
#  when: deploy_custom_plugins == "yes"

- name: "Block to create/set cron jobs needed by Mautic if it is a Production environment being setup"
  block:
    - name: "Setup cron job for Processing Mautic Webhooks"
      cron:
        user: "{{ web_user }}"
        name: "mautic:webhooks:process"
        minute: "0,10,20,30,40,50"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:webhooks:process > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Segment Updates"
      cron:
        user: "{{ web_user }}"
        name: "mautic:segments:update"
        minute: "2,12,22,32,42,52"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:segments:update > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Campaigns"
      cron:
        user: "{{ web_user }}"
        name: "mautic:campaigns:rebuild"
        minute: "4,14,24,34,44,54"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:campaigns:rebuild > /dev/null 2>&1"

    - name: "Setup cron job for Triggering Mautic Campaigns"
      cron:
        user: "{{ web_user }}"
        name: "mautic:campaigns:trigger"
        minute: "6,16,26,36,46,56"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:campaigns:trigger > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Sending Emails"
      cron:
        user: "{{ web_user }}"
        name: "mautic:emails:send"
        minute: "1,11,21,31,41,51"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:emails:send > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Fetching Emails"
      cron:
        user: "{{ web_user }}"
        name: "mautic:email:fetch"
        minute: "3,13,23,33,44,54"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:email:fetch > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Social Monitoring"
      cron:
        user: "{{ web_user }}"
        name: "mautic:social:monitoring"
        minute: "2,12,22,32,42,52"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:social:monitoring > /dev/null 2>&1"

    - name: "Setup cron job for Mautic IP Lookup Download"
      cron:
        user: "{{ web_user }}"
        name: "mautic:iplookup:download"
        minute: "5,15,25,35,45,55"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:iplookup:download > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Maintenance Cleanup"
      cron:
        user: "{{ web_user }}"
        name: "mautic:maintenance:cleanup"
        minute: "0"
        hour: "2"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:maintenance:cleanup --days-old=365 > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Send Broadcasts"
      cron:
        user: "{{ web_user }}"
        name: "mautic:broadcasts:send"
        minute: "7,17,27,37,47,57"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:broadcasts:send > /dev/null 2>&1"

    - name: "Setup cron job for Mautic Fetching SuiteCRM Leads"
      cron:
        user: "{{ web_user }}"
        name: "Fetch Sugarcrm Leads"
        minute: "*"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "php {{ web_files_path }}/app/console mautic:integration:fetchleads --integration=Sugarcrm"
    
  # Only execute the above task block to setup cron jobs if it is a PROD environment 
  when: mautic_dev_env == "no"


- name: "Setting ownership and permissions for web directory"
  file:
    path: "{{ web_files_path }}"
    state: directory
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    recurse: yes

- name: "Removing Git folder from web server permissions"
  file:
    path: "{{ web_files_path }}/.git"
    state: directory
    owner: root
    group: root
    mode: 0640
    recurse: yes

- name: "Removing .gitignore from web server permissions"
  file:
    path: "{{ web_files_path }}/.gitignore"
    state: file
    owner: root
    group: root
    mode: 0640
  notify: finish-mautic-permissions
















