---
# handlers file for git-download-mautic

- name: restart-apache
  service: 
    name: apache2 
    state: restarted

- name: "Clear-mautic-cache"
  become: true
  become_method: sudo
  shell: "rm -rf {{ git_download_mautic_web_files_path }}{{ git_download_mautic_web_directory_for_application }}/app/cache/*"
  listen: "finish-mautic-permissions"

- name: "Set ownership to Apache webuser"
  become: true
  become_method: sudo
  shell: "chown -R {{ git_download_mautic_web_user }}:{{ git_download_mautic_web_group }} {{ git_download_mautic_web_files_path }}{{ git_download_mautic_web_directory_for_application }}"
  listen: "finish-mautic-permissions"

- name: "Set ownership to root for Git files and directory"
  become: true
  become_method: sudo
  shell: "chown -R root:root {{ git_download_mautic_web_files_path }}{{ git_download_mautic_web_directory_for_application }}/.git {{ git_download_mautic_web_files_path }}{{ git_download_mautic_web_directory_for_application }}/.github {{ git_download_mautic_web_files_path }}{{ git_download_mautic_web_directory_for_application }}/.gitignore"
  listen: "finish-mautic-permissions"

- name: "Make Mautic Cache writable and executable"
  become: true
  become_method: sudo
  shell: "chmod -R 755 {{ git_download_mautic_web_files_path }}{{ git_download_mautic_web_directory_for_application }}/app/cache"
  listen: "finish-mautic-permissions"

- name: "Restart Apache for good measure"
  become: true
  become_method: sudo
  service: 
    name: apache2 
    state: restarted
  listen: "finish-mautic-permissions"


